version: "3.9"

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host
